### PR TITLE
adding support to aws sdk 1.10.10

### PR DESCRIPTION
**Pull request by Fsero**
Simply updating aws SDK

### CODE REVIEW

**Comment by Fsero** [comment]
ive just signed the document

**Comment by dadoonet** [comment]
@Fsero Thanks for your PR. Could you open it against [elastic/elasticsearch repo](https://github.com/elastic/elasticsearch/tree/master/plugins/cloud-aws)?

We will most likely merge it there.

**Comment by Fsero** [comment]
@dadoonet done

**Comment by dadoonet** [comment]
Great! Thanks! Closing this one.

**Pull request closed without merging**
