### PR TITLE
adding gov-cloud west to ec2

### PR DESCRIPTION
**Pull request by amos6224**
I would like to add aws gov cloud for service discovery

### CODE REVIEW

**Comment by dadoonet** [comment]
Could you open this PR against elasticsearch repository as the project is moving there?
And also check that you have signed the CLA.

Thanks!

**Comment by dadoonet** [comment]
Was fixed by https://github.com/elastic/elasticsearch/pull/14358.

**Comment by tamsky** [comment]
Would be nice if this could be cherrypicked into the https://github.com/elastic/elasticsearch-cloud-aws/tree/es-1.7 branch.

**Comment by dadoonet** [comment]
1.7 is not supported anymore.

**Comment by tamsky** [comment]
both our statements are true.

**Comment by dadoonet** [comment]
I meant we won’t ever release a new version of elasticsearch 1.7 or this repository.
You can fork the project, add the missing bits, run mvn install and use the artifact.

Better to upgrade elasticsearch IMO.

**Pull request closed without merging**
