### PR TITLE
Add support for S3 StorageClass (Glacier, Reduced Redundancy, Infrequent Access)

### PR DESCRIPTION
**Pull request by schonfeld**
This PR adds support for S3's storage class...

### CODE REVIEW

**Comment by dadoonet** [comment]
Could you open this against elasticsearch repo? It won't be merged in this repo.

Also, if you want to udpate AWS SDK, please do it in another PR (against elasticsearch repo again).
 
Thanks!

**Comment by schonfeld** [comment]
@dadoonet erm, sure... Reason I didn't do it from the start is cos the main es repo requires Java 1.8 to build... Is there a way around that? Otherwise, I'll get that set up in a few days

**Comment by dadoonet** [comment]
Well. You can build it against 2.x branch.

**Comment by dadoonet** [comment]
Fixed with https://github.com/elastic/elasticsearch/pull/13656

**Pull request closed without merging**
