### PR TITLE
improved building of disco nodes

### PR DESCRIPTION
**Pull request by chaudum**
- improved retry policy of ec2 client
- cache results for 10s

### CODE REVIEW

**Comment by chaudum** [comment]
Where can I sign the CLA?

**Comment by dadoonet** [comment]
Thanks for your PR.

Could you please open your PR against elasticsearch repository please?
Also the CLA is here: https://www.elastic.co/contributor-agreement/

**Comment by clintongormley** [comment]
Hi @chaudum 

Did you have a chance to sign the CLA?  I can't find you in the list yet.

**Comment by chaudum** [comment]
@clintongormley @dadoonet 
I've signed the CLA now. Sorry for the delay.

**Comment by dadoonet** [comment]
@chaudum Any chance you could send the same PR to elasticsearch repo and close this one here?

**Comment by gmoskovicz** [comment]
+1 on this

**Comment by gmoskovicz** [comment]
@chaudum any update on this?

Thanks!

**Comment by dadoonet** [comment]
@gmoskovicz we are closed to get this in. See the PR discussion on elasticsearch repo.

**Comment by gmoskovicz** [comment]
Thanks @dadoonet !

**Pull request closed without merging**
